spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
    password: #密码
    database: 1
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 500
        min-idle: 0
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vertical?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: #你的账号
    password: #你的密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    resources:
      add-mappings: true
  mail:
    host: smtp.ym.163.com
    port: 465
    username: #你的邮箱账号
    password: #你的邮箱密码
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
wx:
  miniapp:
    configs:
      - appid: wxf57df4f171606a26
        secret: 574ff86cb48a42f3980b221e942c53b1
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON
env: dev
logging:
  file:
    path: /logs/vertical
  level:
    root: info
server:
  port: 8099
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  max-http-header-size: 1024
version: 1.0
resource:
  file-path: https://rymcu.com/vertical